### ISSUE TITLE
Undefined variable: "$menu_radius"

### ISSUE THREAD

**Issue by ghost** [B00merang-Project/Azurra_framework#1]
Trying out Azurra with directions on the wiki ([https://github.com/Elbullazul/Azurra_framework/wiki/5.-Editing-colors](https://github.com/Elbullazul/Azurra_framework/wiki/5.-Editing-colors)). Getting error running command as show below...

**ssepan@ssepandesktop2:~/Git/Azurra_framework$** _./autogen.sh ganje_
Compiling Ganje

Error: Undefined variable: "$menu_radius".
        on line 5 of Azurra/widgets/_menu.scss, in `menu'
        from line 195 of ganje/_common.scss
        from line 7 of ganje/gtk.scss
  Use --trace for backtrace.
ERROR: SASS exited unexpectedly, aborting

**Comment by Elbullazul** [comment]
oops! I fixed the typo causing the issue

**Comment by ghost** [comment]
Thanks! That error is resolved.
