### ISSUE TITLE
Autogen copy err: no such file or directory, cp: cannot create directory '~/.themes'

### ISSUE THREAD

**Issue by ghost** [B00merang-Project/Azurra_framework#3]
Got further now that issue #1 is resolved. Re-ran ./autogen.sh ganje and got a different error on the copy:

`ssepan@ssepandesktop2:~/Git/Azurra_framework$ **./autogen.sh ganje**
Compiling Ganje

done
Deploying Ganje, cp: cannot create regular file '~/.themes': No such file or directory
cp: cannot create directory '~/.themes': No such file or directory
done

ssepan@ssepandesktop2:~/Git/Azurra_framework$ **sudo ./autogen.sh ganje**
[sudo] password for ssepan:             
Compiling Ganje

done
Deploying Ganje, cp: cannot create regular file '~/.themes': No such file or directory
cp: cannot create directory '~/.themes': No such file or directory
done

ssepan@ssepandesktop2:~/Git/Azurra_framework$ **cd ~/.themes**
ssepan@ssepandesktop2:~/.themes$ **cd -**
/home/ssepan/Git/Azurra_framework
ssepan@ssepandesktop2:~/Git/Azurra_framework$ `

1) I went to the link on the page  
[https://github.com/Elbullazul/Azurra_framework/wiki/5.-Editing-colors](https://github.com/Elbullazul/Azurra_framework/wiki/5.-Editing-colors)
that was called see autoget wiki, but that link only come back to the same page
2) I also tried pre-creating "ganje" folder under "~/.themes", but no change. Actually, step 3 on page 5 talked about creating the folder after running autogen, so it cannot be required in step 2.
3) if i leave the target_dir empty I get 'Empty target for Ganje, skipping deployment'
4) if I use '/home/ssepan/.themes', the process run without complaint: 'Deploying Ganje, done'; assets folder is created under .themes 

-- So, the process likes the explicit path, but not the shortcut version to /home/username

**Comment by Elbullazul** [comment]
See [7. Deployment](https://github.com/Elbullazul/Azurra_framework/wiki/7.-Deployment)

**Comment by Elbullazul** [comment]
Also, I think I meant the compiling command to be ./autogen.sh -c <theme>. Can you point me to the page having the run instructions?

Autogen wiki doesn't exist. I changed that to ./autogen.sh --help

**Comment by ghost** [comment]
Regarding your question, I'm guessing you found that page already, but it was page 5 'Editing Colors' with the command that I was running.

**Comment by ghost** [comment]
Changing the directory setting as descriped in page 7 works, and then running the command differently (with '-c' option) skips the deploy step. Looks OK.

**Comment by ghost** [comment]
Question: I've gotten through page 7, and am able to see changes to the secondary steppers  by setting true or false. The gtk.css and assets folder seems to be generated in the Ganje folder rather than under the gtk-3.0 folder, so must be copied down each time. Is this  to be expected?

**Comment by Elbullazul** [comment]
I should specify that the target variable is to be set as `THEME_NAME/gtk-3.0`

should probably add that to the wiki

**Comment by ghost** [comment]
I added that to the end so it looks like "$HOME/.themes/Ganje/gtk-3.0" and it works great.

**Comment by Elbullazul** [comment]
Ok, will correct the documentation
