### ISSUE TITLE
Wiki page 8: "related" instead of "relied"? (LOW)

### ISSUE THREAD

**Issue by ghost** [B00merang-Project/Azurra_framework#4]
"Note: Since the theme is written is SASS, most CSS rules will work just as you'd expect. Most of the CSS rules that won't work in GNOME CSS are **relied** to placement and spacing."

Looks like a case of rogue spell-checker. ;-)

**Comment by Elbullazul** [comment]
will correct

**Comment by ghost** [comment]
Thx!
PS - no issues on p9, just re-generated the darker check/radio as the tutorial directs -- worked fine!
