### ISSUE TITLE
Add Themes From Java Swing Look And Feel

### ISSUE THREAD

**Issue by cheznewa** [B00merang-Project/Azurra_framework#5]
Hello/Hi Is possible to add themes reproduce the look and feel from java swing, like Metal Nimbus CDE/Motif

Please

Sick/Newa.

**Comment by Elbullazul** [comment]
Metal Nimbus, I assume is Solaris 10's blueprint theme? [It's here](https://github.com/B00merang-Project/Solaris-10).

And Motif/CDE was Solaris 9's desktop environment. [It's here](https://github.com/B00merang-Project/Solaris-10-CDE).

Also, this repo is for the base framework. The themes are hosted on the [B00merang's project repo](https://github.com/B00merang-Project/Azurra_framework)
