### ISSUE TITLE
repo was deprecated

### ISSUE THREAD

**Issue by CouldBeThis** [B00merang-Project/Azurra_framework#6]
I just spent a bunch of time futzing around with this project before finally noticing the note that this repo is deprecated. 

Unless there is some reason not to, I would suggest any or all of the following

- delete the wiki or add a prominent note to the wiki landing page
- change the repo description to include "DEPRECATED"
- add an emoji to the deprecation notice to draw attention

edit: [2. Setup · Elbullazul/Azurra_framework Wiki](https://github.com/Elbullazul/Azurra_framework/wiki/2.-Setup) instructs to clone `Elbullazul/Azurra_framework`. Is that correct?

**Comment by Elbullazul** [comment]
@CouldBeThis you should now use B00merang-Project/Azurra_framework. I copied the repo over there and fixed the links.

I will add a clearer deprecation notice, thanks for the suggestion.

See my answer on #7 for more details.

**Comment by Elbullazul** [comment]
Update: As the B00merang repo was a fork and the original was not keeping up to date, I have recently overwritten the "original" branches with those from the fork. After checking if the commits did indeed copy over to the "original", I deleted the fork and transferred the "original" repo to the B00merang org.

So this repo IS currently supported. Sorry about the confusion this might cause to anyone reading this.
