### ISSUE TITLE
website links to wrong url

### ISSUE THREAD

**Issue by CouldBeThis** [B00merang-Project/Azurra_framework#7]
I ended up in the wrong repo because https://b00merang.weebly.com/azurra-framework.html links to the deprecated wiki

edit: or maybe it is the correct wiki? I am confused.

**Comment by Elbullazul** [comment]
@CouldBeThis the original plan was to have this repo be a "vanilla" implementation, and the b00merang repo be the one where all the work was done. This is why the documentation is on this repo, and why the website links here, Eventually, it became a bit too much work to work on 2 repos at a time, and this one was abandoned.

I just added the wiki to the b00merang repo, and I'll add a big deprecation notice (and maybe archive the repo)
